tools:
  - name: "backstage_mcp_tools"
    url: "https://rolling-demo-backstage-rolling-demo-ns.apps.rosa.redhat-ai-dev.m6no.p3.openshiftapps.com/api/mcp-actions/v1"
    transport: "streamable-http"
    bearerTokenEnvVarName: "RHDH_TOKEN"

